apiVersion: v1
kind: Secret
metadata:
  namespace: kuadrant-system
  name: trlp-tutorial-api-key-free-user-1
  labels:
    authorino.kuadrant.io/managed-by: authorino
    app: my-llm
  annotations:
    kuadrant.io/groups: free
    secret.kuadrant.io/user-id: user-1
stringData:
  api_key: iamafreeuser
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  namespace: kuadrant-system
  name: trlp-tutorial-api-key-gold-user-1
  labels:
    authorino.kuadrant.io/managed-by: authorino
    app: my-llm
  annotations:
    kuadrant.io/groups: gold
    secret.kuadrant.io/user-id: user-2
stringData:
  api_key: iamagolduser
type: Opaque