apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS5yZWRoYXQuaW8iOiB7InVzZXJuYW1lIjogIjUxNTQ4NDgwfHVoYy0xRnJHc0lEVVpRMkR6blNKM2lXMEF0bUxKaDciLCAicGFzc3dvcmQiOiAiZXlKaGJHY2lPaUpTVXpVeE1pSjkuZXlKemRXSWlPaUl6T0daa01XSTRaamMyTmpnME5qSm1ZV000WlRabFlUZ3dPRFEyTjJJM055SjkuWFJkOS0tS0N5M1ZaVWxfZXU3NEx6UDBRMzlWMEVFX3lkWThOaVRkUnFJcndoVUR2LXBRdmRLS1dWaVZpWkFhdEJIRFFXZlQwdWdqX01iM2JjT1JLakl3QTZXUE12MVk3NUZoWEFINUtjMnN5Z0h1cVk0X2ZYUjlyZ21uNjdJdDJoYlFycm9wQTV5WmF6V0s4T3kwSW9vVVhQLXgwT1I2dlQyU1RpLW5ubG5QS2xBUlkwRGZMSWJpNzh2ZWVxWnVKclA5eEs5V3Z0WjhGTkRKc0J5VHNlZnhUaFZrSzA1cFQ5YU5PZ05MSExiTHlObHRHNURPcVNSYmdYSzAyekVzWlNwcGJmS3VQMDVSWEFpY0MteFhGYmprS2haZGE4MFd5Z2QySnE2V1lRd1lvN2V4LS1IdTBKSnlwU3M0SDVWNDZudHUzVUZTVVBEQWRCeVZlQ1NkcXJKc1FmaEppaS1XSW13Y1p6ei1DcE5UXzVaNHotVlJHNGlfYVRfU1p1ZEM1ckphS3RaR0tUUFpYNEg5TS1sQ3hZR2QyTWM4blpXODVlVHkyT2JwVThwNktfbFNwN1pteUc4RG1oemxQLWE0M29CdVd4SUx4N2NvN1NwZDhUcmFTUW41Z2hab3NFSmRqel9pY05RYVZLTWsxR0IxMG1NbjlyQXhnVHJualNPWkhGb3F3Zl9mNnZ2RVotMklKdkJPdVFGUUE4bGQ5c0Q1Q29WVjRHcE1sdUZfM2RianF4blUxNFl3R09kYUpXUjhLTE5RcG1PUVdCa1hSSHFacDdNVE9GQ19HTFQ0VnhjUzF4b2tKekVBcTdXODcwUkFaOFZwLVBnbHBCQnNkQ09rX3RjQjRGOU9oZGdDT29yTDRyZGZqenBCaG1GbjBIc1ZBRTRiZGloX0YzRkkifQogIH0KfQo=
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/instance: ingress-gateway
  name: wasm-plugin-pull-secret
  namespace: gateway-system
type: kubernetes.io/dockerconfigjson
