apiVersion: v1
data:
  
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/instance: gateway-system
  name: wasm-plugin-pull-secret
  namespace: gateway-system
type: kubernetes.io/dockerconfigjson
