apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-gateway
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gateway
    repoURL: https://github.com/bugbiteme/rhcl-ai-llm-policies
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
